// Auto-generated by level-editor — edit via level-editor
LEVELS_CLEANINGXL = [
  {
    "id": 1,
    "cols": 4,
    "rows": 4,
    "colorCount": 3,
    "turns": 15,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "colors": [
      [
        0,
        0,
        "red"
      ],
      [
        0,
        1,
        "red"
      ],
      [
        1,
        2,
        "red"
      ],
      [
        1,
        3,
        "red"
      ],
      [
        1,
        1,
        "green"
      ],
      [
        3,
        1,
        "green"
      ],
      [
        3,
        2,
        "green"
      ],
      [
        2,
        2,
        "green"
      ],
      [
        2,
        1,
        "green"
      ],
      [
        0,
        2,
        "blue"
      ],
      [
        0,
        3,
        "blue"
      ],
      [
        2,
        3,
        "blue"
      ],
      [
        3,
        3,
        "blue"
      ],
      [
        1,
        0,
        "blue"
      ],
      [
        2,
        0,
        "blue"
      ],
      [
        3,
        0,
        "blue"
      ]
    ]
  },
  {
    "id": 2,
    "cols": 4,
    "rows": 4,
    "colorCount": 3,
    "turns": 15,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "colors": [
      [
        1,
        1,
        "red"
      ],
      [
        2,
        2,
        "blue"
      ],
      [
        3,
        2,
        "blue"
      ],
      [
        1,
        2,
        "green"
      ],
      [
        2,
        1,
        "green"
      ],
      [
        1,
        0,
        "green"
      ],
      [
        2,
        0,
        "green"
      ],
      [
        3,
        0,
        "green"
      ],
      [
        3,
        1,
        "green"
      ],
      [
        0,
        1,
        "green"
      ],
      [
        1,
        3,
        "red"
      ],
      [
        0,
        0,
        "blue"
      ],
      [
        3,
        3,
        "red"
      ],
      [
        2,
        3,
        "blue"
      ],
      [
        0,
        2,
        "red"
      ],
      [
        0,
        3,
        "red"
      ]
    ]
  },
  {
    "id": 3,
    "cols": 4,
    "rows": 4,
    "colorCount": 3,
    "turns": 15,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 4,
    "cols": 4,
    "rows": 5,
    "colorCount": 3,
    "turns": 20,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "colors": [
      [
        2,
        0,
        "green"
      ],
      [
        3,
        2,
        "green"
      ],
      [
        1,
        2,
        "green"
      ],
      [
        4,
        0,
        "green"
      ],
      [
        4,
        1,
        "green"
      ]
    ],
    "colorCounts": {
      "green": 7
    }
  },
  {
    "id": 5,
    "cols": 4,
    "rows": 5,
    "colorCount": 4,
    "turns": 20,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 6,
    "cols": 5,
    "rows": 10,
    "colorCount": 2,
    "turns": 15,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "disabled": [
      [
        2,
        1
      ],
      [
        2,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        2,
        3
      ],
      [
        9,
        1
      ],
      [
        9,
        0
      ],
      [
        8,
        0
      ],
      [
        7,
        0
      ],
      [
        7,
        1
      ],
      [
        9,
        3
      ],
      [
        9,
        4
      ],
      [
        7,
        4
      ],
      [
        7,
        3
      ],
      [
        6,
        0
      ],
      [
        6,
        1
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ],
      [
        6,
        4
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        4
      ],
      [
        3,
        3
      ],
      [
        8,
        4
      ]
    ],
    "colors": [
      [
        4,
        0,
        "red"
      ],
      [
        4,
        1,
        "red"
      ],
      [
        4,
        2,
        "red"
      ],
      [
        4,
        3,
        "red"
      ],
      [
        4,
        4,
        "red"
      ],
      [
        7,
        2,
        "red"
      ],
      [
        8,
        2,
        "red"
      ],
      [
        9,
        2,
        "red"
      ],
      [
        8,
        1,
        "red"
      ],
      [
        8,
        3,
        "red"
      ],
      [
        5,
        0,
        "green"
      ],
      [
        5,
        1,
        "green"
      ],
      [
        5,
        2,
        "green"
      ],
      [
        5,
        3,
        "green"
      ],
      [
        5,
        4,
        "green"
      ],
      [
        0,
        2,
        "green"
      ],
      [
        1,
        1,
        "green"
      ],
      [
        2,
        2,
        "green"
      ],
      [
        1,
        2,
        "green"
      ],
      [
        1,
        3,
        "green"
      ]
    ]
  },
  {
    "id": 7,
    "cols": 5,
    "rows": 5,
    "colorCount": 3,
    "turns": 25,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 8,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 25,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "colors": [
      [
        1,
        0,
        "red"
      ],
      [
        0,
        0,
        "red"
      ],
      [
        0,
        1,
        "red"
      ],
      [
        0,
        2,
        "red"
      ],
      [
        0,
        3,
        "red"
      ],
      [
        0,
        4,
        "red"
      ],
      [
        1,
        4,
        "red"
      ],
      [
        2,
        2,
        "red"
      ]
    ],
    "colorCounts": {
      "red": 8
    }
  },
  {
    "id": 9,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 20,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 10,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 20,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "colors": [
      [
        4,
        4,
        "blue"
      ],
      [
        4,
        3,
        "blue"
      ],
      [
        4,
        0,
        "blue"
      ],
      [
        4,
        1,
        "blue"
      ],
      [
        0,
        1,
        "blue"
      ],
      [
        0,
        3,
        "blue"
      ],
      [
        1,
        0,
        "blue"
      ],
      [
        1,
        4,
        "blue"
      ],
      [
        3,
        4,
        "blue"
      ],
      [
        3,
        0,
        "blue"
      ]
    ],
    "colorCounts": {
      "blue": 10
    }
  },
  {
    "id": 11,
    "cols": 5,
    "rows": 7,
    "colorCount": 4,
    "turns": 15,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "disabled": [
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        3,
        0
      ],
      [
        4,
        3
      ],
      [
        4,
        4
      ],
      [
        3,
        4
      ],
      [
        6,
        2
      ],
      [
        5,
        2
      ]
    ],
    "colors": [
      [
        0,
        0,
        "blue"
      ],
      [
        0,
        1,
        "blue"
      ],
      [
        1,
        1,
        "blue"
      ],
      [
        1,
        0,
        "blue"
      ],
      [
        0,
        3,
        "yellow"
      ],
      [
        0,
        4,
        "yellow"
      ],
      [
        1,
        4,
        "yellow"
      ],
      [
        1,
        3,
        "yellow"
      ],
      [
        5,
        0,
        "red"
      ],
      [
        5,
        1,
        "red"
      ],
      [
        6,
        0,
        "red"
      ],
      [
        6,
        1,
        "red"
      ],
      [
        4,
        2,
        "red"
      ],
      [
        5,
        3,
        "green"
      ],
      [
        6,
        3,
        "green"
      ],
      [
        6,
        4,
        "green"
      ],
      [
        5,
        4,
        "green"
      ],
      [
        3,
        3,
        "green"
      ],
      [
        3,
        1,
        "blue"
      ],
      [
        2,
        2,
        "yellow"
      ]
    ]
  },
  {
    "id": 12,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 25,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      },
      {
        "type": "orderedCards",
        "count": 2,
        "positions": [
          [
            5,
            1
          ],
          [
            5,
            4
          ]
        ]
      }
    ]
  },
  {
    "id": 13,
    "cols": 5,
    "rows": 6,
    "colorCount": 4,
    "turns": 25,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 14,
    "cols": 5,
    "rows": 6,
    "colorCount": 5,
    "turns": 25,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 15,
    "cols": 5,
    "rows": 7,
    "colorCount": 5,
    "turns": 30,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "colors": [
      [
        3,
        0,
        "green"
      ],
      [
        3,
        4,
        "green"
      ],
      [
        0,
        0,
        "red"
      ],
      [
        1,
        0,
        "red"
      ],
      [
        2,
        0,
        "red"
      ],
      [
        4,
        0,
        "red"
      ],
      [
        5,
        0,
        "red"
      ],
      [
        6,
        0,
        "red"
      ],
      [
        6,
        4,
        "red"
      ],
      [
        5,
        4,
        "red"
      ],
      [
        4,
        4,
        "red"
      ],
      [
        2,
        4,
        "red"
      ],
      [
        0,
        4,
        "red"
      ],
      [
        1,
        4,
        "red"
      ]
    ],
    "colorCounts": {
      "red": 12,
      "green": 2
    },
    "backEffects": [
      [
        3,
        0,
        "column"
      ],
      [
        3,
        4,
        "column"
      ]
    ]
  },
  {
    "id": 16,
    "cols": 5,
    "rows": 5,
    "colorCount": 5,
    "turns": 20,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "backEffects": [
      [
        2,
        2,
        "star"
      ],
      [
        4,
        4,
        "cross"
      ],
      [
        4,
        0,
        "cross"
      ],
      [
        0,
        0,
        "cross"
      ],
      [
        0,
        4,
        "cross"
      ]
    ]
  },
  {
    "id": 17,
    "cols": 5,
    "rows": 7,
    "colorCount": 4,
    "turns": 25,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "disabled": [
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        3
      ],
      [
        5,
        2
      ],
      [
        4,
        1
      ],
      [
        3,
        0
      ]
    ],
    "backEffects": [
      [
        3,
        2,
        "cross"
      ],
      [
        6,
        2,
        "row"
      ]
    ]
  },
  {
    "id": 18,
    "cols": 7,
    "rows": 5,
    "colorCount": 4,
    "turns": 25,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "disabled": [
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        4
      ],
      [
        1,
        3
      ],
      [
        3,
        3
      ]
    ],
    "backEffects": [
      [
        2,
        6,
        "circle"
      ],
      [
        2,
        0,
        "circle"
      ]
    ]
  },
  {
    "id": 19,
    "cols": 5,
    "rows": 7,
    "colorCount": 4,
    "turns": 15,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "disabled": [
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ],
      [
        3,
        4
      ],
      [
        2,
        2
      ],
      [
        4,
        2
      ]
    ],
    "colorCounts": {
      "yellow": 3
    },
    "backEffects": [
      [
        0,
        4,
        "column"
      ],
      [
        7,
        0,
        "column"
      ],
      [
        6,
        0,
        "column"
      ]
    ]
  },
  {
    "id": 20,
    "cols": 7,
    "rows": 7,
    "colorCount": 4,
    "turns": 20,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "disabled": [
      [
        3,
        3
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        5,
        3
      ],
      [
        5,
        4
      ],
      [
        5,
        5
      ],
      [
        4,
        5
      ],
      [
        2,
        5
      ],
      [
        1,
        5
      ],
      [
        1,
        1
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ],
      [
        1,
        2
      ],
      [
        5,
        2
      ],
      [
        3,
        5
      ]
    ],
    "backEffects": [
      [
        6,
        3,
        "row"
      ],
      [
        0,
        3,
        "row"
      ],
      [
        3,
        6,
        "column"
      ],
      [
        3,
        0,
        "column"
      ]
    ]
  },
  {
    "id": 21,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 22,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 23,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 24,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 25,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 26,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 27,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 28,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 29,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 30,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 31,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 32,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 33,
    "cols": 8,
    "rows": 8,
    "colorCount": 4,
    "turns": 58,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 34,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 35,
    "cols": 7,
    "rows": 9,
    "colorCount": 4,
    "turns": 57,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 36,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 37,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 38,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 39,
    "cols": 7,
    "rows": 9,
    "colorCount": 4,
    "turns": 57,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 40,
    "cols": 8,
    "rows": 9,
    "colorCount": 4,
    "turns": 65,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 41,
    "cols": 7,
    "rows": 6,
    "colorCount": 4,
    "turns": 38,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  }
];
