// Auto-generated by level-editor — edit via level-editor
PROGRESSION_CLEANING_XL = {
  "winStreakStartLevel": 11,
  "deploySpecialsStartLevel": 1000,
  "recallStartLevel": 16,
  "sweepRevealStartLevel": 1000,
  "levelRewards": [
    {
      "afterLevel": 1,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 3,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 6,
      "boosterId": "peek",
      "qty": 1
    },
    {
      "afterLevel": 9,
      "boosterId": "pluscolor",
      "qty": 10
    },
    {
      "afterLevel": 11,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 20,
      "boosterId": "pluscolor",
      "qty": 1
    },
    {
      "afterLevel": 25,
      "boosterId": "random3",
      "qty": 1
    },
    {
      "afterLevel": 28,
      "boosterId": "random3",
      "qty": 1
    },
    {
      "afterLevel": 34,
      "boosterId": "pluscolor",
      "qty": 1
    },
    {
      "afterLevel": 41,
      "boosterId": "pluscolor",
      "qty": 1
    },
    {
      "afterLevel": 46,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 50,
      "boosterId": "pluscolor",
      "qty": 1
    },
    {
      "afterLevel": 59,
      "boosterId": "random3",
      "qty": 1
    },
    {
      "afterLevel": 69,
      "boosterId": "pluscolor",
      "qty": 1
    },
    {
      "afterLevel": 75,
      "boosterId": "pluscolor",
      "qty": 1
    },
    {
      "afterLevel": 84,
      "boosterId": "random3",
      "qty": 1
    },
    {
      "afterLevel": 95,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 99,
      "boosterId": "pluscolor",
      "qty": 1
    }
  ]
};
