// Auto-generated by level-editor — edit via level-editor
PROGRESSION_SHORT = {
  "winStreakStartLevel": 17,
  "deploySpecialsStartLevel": 5,
  "recallStartLevel": 3,
  "sweepRevealStartLevel": 16,
  "levelRewards": [
    {
      "afterLevel": 1,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 2,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 2,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 3,
      "boosterId": "random3",
      "qty": 1
    },
    {
      "afterLevel": 4,
      "type": "special",
      "specialId": "cross",
      "qty": 1
    },
    {
      "afterLevel": 5,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 6,
      "qty": 1,
      "type": "special",
      "specialId": "wild"
    },
    {
      "afterLevel": 7,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 8,
      "qty": 1,
      "boosterId": "joker"
    },
    {
      "afterLevel": 9,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 9,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 10,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 10,
      "type": "special",
      "specialId": "ring",
      "qty": 1
    },
    {
      "afterLevel": 11,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 11,
      "type": "special",
      "specialId": "wild",
      "qty": 1
    },
    {
      "afterLevel": 12,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 13,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 13,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 14,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 14,
      "qty": 1,
      "type": "special",
      "specialId": "wild"
    },
    {
      "afterLevel": 14,
      "qty": 1,
      "type": "special",
      "specialId": "cross"
    },
    {
      "afterLevel": 14,
      "qty": 1,
      "type": "special",
      "specialId": "ring"
    },
    {
      "afterLevel": 15,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 15,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 15,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 16,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 17,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 17,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 18,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 19,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 20,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 20,
      "type": "special",
      "specialId": "cross",
      "qty": 1
    },
    {
      "afterLevel": 21,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 22,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 23,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 23,
      "type": "special",
      "specialId": "ring",
      "qty": 1
    },
    {
      "afterLevel": 24,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 24,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 25,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 26,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 27,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 27,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 28,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 29,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 30,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 30,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 31,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 32,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 33,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 33,
      "type": "special",
      "specialId": "ring",
      "qty": 1
    },
    {
      "afterLevel": 34,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 34,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 35,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 36,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 36,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 37,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 37,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 38,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 38,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 38,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 38,
      "type": "special",
      "specialId": "ring",
      "qty": 1
    },
    {
      "afterLevel": 38,
      "qty": 1,
      "type": "special",
      "specialId": "cross"
    }
  ]
};
