// Auto-generated by level-editor — edit via level-editor
PROGRESSION_UNLOCK_LEVELS = {
  "winStreakStartLevel": 10,
  "deploySpecialsStartLevel": 5,
  "recallStartLevel": 2,
  "sweepRevealStartLevel": 9
};

DEFAULT_LEVEL_REWARDS = [
  {
    "afterLevel": 1,
    "boosterId": "peek",
    "qty": 3
  },
  {
    "afterLevel": 2,
    "boosterId": "peek",
    "qty": 3
  }
];
