// Auto-generated by level-editor — edit via level-editor
LEVELS_CLEANINGXL = [
  {
    "id": 1,
    "cols": 4,
    "rows": 6,
    "colorCount": 3,
    "turns": 22,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 2,
    "cols": 4,
    "rows": 6,
    "colorCount": 3,
    "turns": 22,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 3,
    "cols": 4,
    "rows": 6,
    "colorCount": 3,
    "turns": 22,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 4,
    "cols": 4,
    "rows": 6,
    "colorCount": 4,
    "turns": 22,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 5,
    "cols": 5,
    "rows": 8,
    "colorCount": 3,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 6,
    "cols": 4,
    "rows": 6,
    "colorCount": 3,
    "turns": 22,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 7,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 8,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 9,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 10,
    "cols": 5,
    "rows": 6,
    "colorCount": 3,
    "turns": 27,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "locked": [
      [
        1,
        1
      ],
      [
        3,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        3
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        2
      ]
    ],
    "disabled": [
      [
        4,
        4
      ],
      [
        4,
        3
      ],
      [
        4,
        2
      ],
      [
        4,
        1
      ],
      [
        4,
        0
      ]
    ]
  },
  {
    "id": 11,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      },
      {
        "type": "orderedCards",
        "count": 4,
        "positions": [
          [
            2,
            1
          ],
          [
            2,
            4
          ],
          [
            5,
            1
          ],
          [
            5,
            4
          ]
        ]
      }
    ]
  },
  {
    "id": 12,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "locked": [
      [
        3,
        2,
        4
      ],
      [
        7,
        2,
        3
      ],
      [
        0,
        2,
        2
      ]
    ]
  },
  {
    "id": 13,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "stacks": [
      [
        3,
        2,
        3
      ],
      [
        4,
        2,
        3
      ],
      [
        4,
        3,
        3
      ],
      [
        3,
        3,
        3
      ]
    ]
  },
  {
    "id": 14,
    "cols": 5,
    "rows": 8,
    "colorCount": 5,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 15,
    "cols": 6,
    "rows": 9,
    "colorCount": 6,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 16,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "elevators": [
      {
        "cells": [
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            3,
            3
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ]
        ],
        "refills": 2
      },
      {
        "cells": [
          [
            6,
            2
          ],
          [
            6,
            3
          ],
          [
            7,
            3
          ],
          [
            7,
            2
          ]
        ],
        "refills": 1
      }
    ]
  },
  {
    "id": 17,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "ice": [
      {
        "cells": [
          [
            3,
            1
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            3,
            3
          ]
        ],
        "threshold": 10
      },
      {
        "cells": [
          [
            6,
            1
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ]
        ],
        "threshold": 2
      }
    ]
  },
  {
    "id": 18,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ],
    "colorLocks": [
      {
        "cells": [
          [
            2,
            1
          ],
          [
            3,
            1
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            3,
            3
          ],
          [
            3,
            2
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ]
        ],
        "color": "blue",
        "count": 3
      }
    ]
  },
  {
    "id": 19,
    "cols": 7,
    "rows": 9,
    "colorCount": 4,
    "turns": 57,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 20,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 21,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 22,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 23,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 24,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 25,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 26,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 27,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 28,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 29,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 30,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 31,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 32,
    "cols": 8,
    "rows": 8,
    "colorCount": 4,
    "turns": 58,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 33,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 34,
    "cols": 7,
    "rows": 9,
    "colorCount": 4,
    "turns": 57,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 35,
    "cols": 5,
    "rows": 8,
    "colorCount": 4,
    "turns": 36,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 36,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 37,
    "cols": 6,
    "rows": 9,
    "colorCount": 4,
    "turns": 49,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 38,
    "cols": 7,
    "rows": 9,
    "colorCount": 4,
    "turns": 57,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 39,
    "cols": 8,
    "rows": 9,
    "colorCount": 4,
    "turns": 65,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  },
  {
    "id": 40,
    "cols": 7,
    "rows": 6,
    "colorCount": 4,
    "turns": 38,
    "clearBoard": true,
    "deck": 0,
    "goals": [
      {
        "type": "clearAll"
      }
    ]
  }
];
