// Auto-generated by level-editor — edit via level-editor
LEVELS = [
  {
    "id": 1,
    "cols": 4,
    "rows": 4,
    "colorCount": 3,
    "turns": 12,
    "goals": [
      {
        "type": "score",
        "target": 250
      }
    ]
  },
  {
    "id": 2,
    "cols": 4,
    "rows": 4,
    "colorCount": 3,
    "turns": 10,
    "goals": [
      {
        "type": "colorCollect",
        "requirements": {
          "red": 4,
          "green": 3
        }
      }
    ]
  },
  {
    "id": 3,
    "cols": 4,
    "rows": 4,
    "colorCount": 4,
    "turns": 14,
    "goals": [
      {
        "type": "specificCombos",
        "minLength": 4,
        "count": 2
      }
    ]
  },
  {
    "id": 4,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 13,
    "goals": [
      {
        "type": "markedCards",
        "totalToCollect": 5,
        "onBoardCount": 3
      }
    ]
  },
  {
    "id": 5,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 11,
    "goals": [
      {
        "type": "score",
        "target": 400
      },
      {
        "type": "colorAvoid",
        "color": "yellow",
        "maxFlips": 3
      }
    ]
  },
  {
    "id": 6,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 14,
    "goals": [
      {
        "type": "score",
        "target": 300
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ]
  },
  {
    "id": 7,
    "cols": 5,
    "rows": 5,
    "colorCount": 4,
    "turns": 12,
    "goals": [
      {
        "type": "score",
        "target": 700
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ]
  },
  {
    "id": 8,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 15,
    "goals": [
      {
        "type": "orderedCards",
        "count": 4,
        "positions": [
          [
            0,
            0
          ],
          [
            1,
            5
          ],
          [
            4,
            0
          ],
          [
            5,
            5
          ]
        ]
      }
    ]
  },
  {
    "id": 9,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 13,
    "goals": [
      {
        "type": "score",
        "target": 1000
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ]
  },
  {
    "id": 10,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 12,
    "goals": [
      {
        "type": "rowCoverage",
        "rows": [
          1,
          2,
          1,
          1,
          2,
          1
        ]
      }
    ]
  },
  {
    "id": 11,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 14,
    "goals": [
      {
        "type": "score",
        "target": 1100
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ]
  },
  {
    "id": 12,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 12,
    "goals": [
      {
        "type": "score",
        "target": 1200
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ]
  },
  {
    "id": 13,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 10,
    "goals": [
      {
        "type": "colCoverage",
        "cols": [
          1,
          1,
          2,
          2,
          1,
          1
        ]
      }
    ]
  },
  {
    "id": 14,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 12,
    "goals": [
      {
        "type": "score",
        "target": 1400
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ]
  },
  {
    "id": 15,
    "cols": 6,
    "rows": 6,
    "colorCount": 4,
    "turns": 10,
    "goals": [
      {
        "type": "score",
        "target": 1600
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ]
  },
  {
    "id": 16,
    "cols": 10,
    "rows": 10,
    "colorCount": 4,
    "turns": 10,
    "goals": [
      {
        "type": "score",
        "target": 500
      },
      {
        "type": "breakLocks",
        "locked": []
      }
    ],
    "disabled": [
      [
        0,
        9
      ],
      [
        1,
        9
      ],
      [
        2,
        9
      ],
      [
        0,
        8
      ],
      [
        1,
        8
      ],
      [
        2,
        8
      ],
      [
        3,
        9
      ],
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        0,
        7
      ],
      [
        1,
        7
      ],
      [
        2,
        7
      ]
    ]
  }
];
