// Auto-generated by level-editor — edit via level-editor
PROGRESSION_LONG = {
  "winStreakStartLevel": 80,
  "deploySpecialsStartLevel": 15,
  "recallStartLevel": 7,
  "sweepRevealStartLevel": 79,
  "levelRewards": [
    {
      "afterLevel": 1,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 3,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 6,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 7,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 9,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 12,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 14,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 15,
      "type": "special",
      "specialId": "wild",
      "qty": 1
    },
    {
      "afterLevel": 15,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 17,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 20,
      "type": "special",
      "specialId": "wild",
      "qty": 1
    },
    {
      "afterLevel": 21,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 23,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 26,
      "type": "special",
      "specialId": "wild",
      "qty": 1
    },
    {
      "afterLevel": 28,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 29,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 31,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 34,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 36,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 39,
      "type": "special",
      "specialId": "cross",
      "qty": 1
    },
    {
      "afterLevel": 40,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 42,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 43,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 43,
      "type": "special",
      "specialId": "wild",
      "qty": 1
    },
    {
      "afterLevel": 45,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 48,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 50,
      "type": "special",
      "specialId": "cross",
      "qty": 1
    },
    {
      "afterLevel": 53,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 54,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 55,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 57,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 60,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 62,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 65,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 67,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 68,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 68,
      "type": "special",
      "specialId": "wild",
      "qty": 1
    },
    {
      "afterLevel": 70,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 73,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 75,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 78,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 79,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 80,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 80,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 82,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 85,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 87,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 90,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 91,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 92,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 94,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 97,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 99,
      "type": "special",
      "specialId": "cross",
      "qty": 1
    },
    {
      "afterLevel": 102,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 104,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 105,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 106,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 108,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 111,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 113,
      "type": "special",
      "specialId": "cross",
      "qty": 1
    },
    {
      "afterLevel": 116,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 118,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 119,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 121,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 124,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 124,
      "type": "special",
      "specialId": "ring",
      "qty": 1
    },
    {
      "afterLevel": 126,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 129,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 130,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 131,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 133,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 136,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 138,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 141,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 143,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 144,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 144,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 146,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 149,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 151,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 154,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 155,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 156,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 158,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 161,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 163,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 166,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 168,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 169,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 169,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 171,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 174,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 176,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 179,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 180,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 181,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 181,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 183,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 186,
      "boosterId": "row",
      "qty": 1
    },
    {
      "afterLevel": 188,
      "boosterId": "col",
      "qty": 1
    },
    {
      "afterLevel": 191,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 192,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 193,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 195,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 198,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 200,
      "type": "special",
      "specialId": "ring",
      "qty": 1
    },
    {
      "afterLevel": 203,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 204,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 205,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 205,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 207,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 210,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 212,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 215,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 217,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 218,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 218,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 220,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 223,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 223,
      "type": "special",
      "specialId": "ring",
      "qty": 1
    },
    {
      "afterLevel": 225,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 228,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 229,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 230,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 230,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 232,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 235,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 237,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 240,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 241,
      "boosterId": "random3",
      "qty": 3
    },
    {
      "afterLevel": 242,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 242,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 244,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 244,
      "boosterId": "random3",
      "qty": 2
    },
    {
      "afterLevel": 247,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 247,
      "type": "special",
      "specialId": "diamond",
      "qty": 1
    },
    {
      "afterLevel": 249,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 249,
      "boosterId": "peek",
      "qty": 2
    },
    {
      "afterLevel": 252,
      "boosterId": "colorpick",
      "qty": 1
    },
    {
      "afterLevel": 253,
      "boosterId": "peek",
      "qty": 3
    },
    {
      "afterLevel": 253,
      "boosterId": "joker",
      "qty": 1
    },
    {
      "afterLevel": 253,
      "type": "special",
      "specialId": "diamond",
      "qty": 1
    }
  ]
};
