#!/usr/bin/env python3
"""Register hall 19 — Wedding Chapel — in collections.

Run from `memory-match/art/tools/` AFTER extract_layer.py has written every
`art/weddingchapel/scene/<key>.png` (+ tight `art/weddingchapel/<key>.png`) and
check_hall_layers.py reports no collisions (see RUNLOG-weddingchapel.md):

    python3 add_halls_19.py --dry-run     # report only, touch nothing
    python3 add_halls_19.py

Sibling of add_halls_9_11.py / add_halls_12_16.py / add_halls_17_18.py: same
idea, one new hall with 9 items, closing the levels-92-100 gap left at the tail
of the journey after Writer's Study..Sweet Shop were renumbered down by 3 to
close the middle 52-54 gap. Deliberately a separate file so re-running one
cannot undo another. Does **not** touch any existing hall, item or boardArt
entry, so it cannot renumber levels or shift the `seenHall` / `seenInstruments`
indices that `progress` is keyed by (see the migration rules in
../../CLAUDE.md §10).

Per item it writes `file` (the 512px keyed PNG, for the behind-board reveal) +
`view` (that PNG's pixel size) + `layer` (the full-canvas scene PNG). Per slot
it writes only `item`, `levelId` and `kind: 'layer'`. `shadow/glow/notes: false`:
all three are inert for a layer slot.

**boardArt is written only for levels that exist** in levels_cleaningxl.json at
the moment the script runs — same graceful-degradation rule as the other
add_halls_*.py scripts.

Idempotent: re-running rewrites the hall in place, keeping whatever `levelId`s
collections.json already has.

Writes both twins byte-identically to what the level-editor's Collections tab
produces:
    collections.json = json.dumps(COLL, indent=2, ensure_ascii=False)   [no \\n]
    collections.js   = 4-line header + "COLLECTIONS = " + that + ";\\n"
"""

import argparse
import json
import os
import sys

from PIL import Image

MM = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
JSON_PATH = os.path.join(MM, "collections.json")
JS_PATH = os.path.join(MM, "collections.js")
LEVELS_PATH = os.path.join(MM, "levels", "levels_cleaningxl.json")

JS_HEADER = (
    "// Collections — item art registry, home halls, and per-level board art.\n"
    "// Single source of truth for home-room.js (main menu) and board-bg.js (art\n"
    "// revealed behind the board). Mirrors collections.json.\n"
    "// Auto-generated by level-editor — edit there; hand-edits get overwritten.\n"
)

# Slot order IS level order. Item keys were checked collision-free against the
# existing 111-item registry before the art was generated.
HALL = {
    "id": "weddingchapel",
    "name": "Wedding Chapel",
    "backdrop": "art/backdrops/weddingchapel.jpeg",
    "first": 92,
    "items": [
        ("weddingrings", "Wedding Rings"),
        ("bridalbouquet", "Bridal Bouquet"),
        ("veiltiara", "Veil & Tiara"),
        ("unitycandle", "Unity Candle"),
        ("guestbook", "Guest Book"),
        ("champagneflutes", "Champagne Flutes"),
        ("weddingcake", "Wedding Cake"),
        ("confettibasket", "Petal Confetti Basket"),
        ("weddingbells", "Wedding Bells"),
    ],
}

# Matches every other backdrop hall's board art: centred, 82% of the board box.
BOARD_ART = {"cx": 0.5, "cy": 0.5, "h": 0.82}

# A layer is drawn cover-cropped to fill the picture box, so its aspect must match
# the backdrop's or every object in the hall shifts. This is the one preflight
# failure that is invisible in the data and obvious on screen.
ASPECT_TOL = 0.005


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def save(coll):
    body = json.dumps(coll, indent=2, ensure_ascii=False)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        f.write(body)
    with open(JS_PATH, "w", encoding="utf-8") as f:
        f.write(JS_HEADER + "COLLECTIONS = " + body + ";\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    coll = load(JSON_PATH)
    spec = dict(HALL)
    existing = {h["id"] for h in coll["halls"]}
    by_id = {h["id"]: h for h in coll["halls"]}

    # LEVEL IDS BELONG TO THE DATA, NOT TO THIS SCRIPT — see add_halls_9_11.py's
    # comment for why. On first run (hall doesn't exist yet) the seed `first`
    # value above is used as-is.
    hall = by_id.get(spec["id"])
    if hall and hall.get("slots"):
        ids = [s["levelId"] for s in hall["slots"]]
        if ids != [spec["first"] + i for i in range(len(spec["items"]))]:
            print("  %-14s keeping the level ids already in collections.json: %s (seed said %d-%d)"
                  % (spec["id"], ids, spec["first"], spec["first"] + len(spec["items"]) - 1))
            spec["first"] = ids[0]
            spec["level_ids"] = ids

    levels = load(LEVELS_PATH)
    level_ids = {lv["id"] for lv in (levels["levels"] if isinstance(levels, dict) else levels)}

    def level_id_at(i):
        return spec.get("level_ids", [spec["first"] + j for j in range(len(spec["items"]))])[i]

    problems, plan = [], []
    backdrop = os.path.join(MM, spec["backdrop"])
    if not os.path.isfile(backdrop):
        problems.append("%s: missing backdrop %s" % (spec["id"], spec["backdrop"]))
    else:
        bw, bh = Image.open(backdrop).size

        for i, (key, name) in enumerate(spec["items"]):
            level = level_id_at(i)
            tight_rel = "art/%s/%s.png" % (spec["id"], key)
            layer_rel = "art/%s/scene/%s.png" % (spec["id"], key)
            tight_abs, layer_abs = os.path.join(MM, tight_rel), os.path.join(MM, layer_rel)

            # An item key already in the registry would be a silent collision: two
            # halls would draw the same art and boardArt would be ambiguous.
            if key in coll["items"] and spec["id"] not in existing:
                problems.append("item key %r is already registered — rename it" % key)
            for rel, abs_ in ((tight_rel, tight_abs), (layer_rel, layer_abs)):
                if not os.path.isfile(abs_):
                    problems.append("%s: missing %s" % (spec["id"], rel))
            if not (os.path.isfile(tight_abs) and os.path.isfile(layer_abs)):
                continue

            tim, lim = Image.open(tight_abs), Image.open(layer_abs)
            for rel, im in ((tight_rel, tim), (layer_rel, lim)):
                if im.mode != "RGBA":
                    problems.append("%s is %s, expected RGBA" % (rel, im.mode))
            delta = abs(lim.size[0] / lim.size[1] - bw / bh)
            if delta > ASPECT_TOL:
                problems.append(
                    "%s aspect %.4f vs backdrop %.4f (off by %.4f) — every item in "
                    "the hall will mis-register" % (layer_rel, lim.size[0] / lim.size[1],
                                                    bw / bh, delta))

            # A levelId may live in only one hall (CLAUDE.md §3).
            for other in coll["halls"]:
                if other["id"] == spec["id"]:
                    continue
                for slot in other["slots"]:
                    if slot["levelId"] == level:
                        problems.append("level %d is already claimed by hall %s"
                                        % (level, other["id"]))
            plan.append((key, name, level, tight_rel, layer_rel, tim.size, lim.size))

    if problems:
        print("PREFLIGHT FAILED:", file=sys.stderr)
        for p in sorted(set(problems)):
            print("  - " + p, file=sys.stderr)
        return 1

    for key, name, level, tight_rel, layer_rel, tsize, lsize in plan:
        coll["items"][key] = {
            "name": name,
            "file": tight_rel,
            "view": {"w": tsize[0], "h": tsize[1]},
            "layer": layer_rel,
        }
        print("  %-10s %-22s L%-3d layer %dx%d  file %dx%d" %
              (spec["id"], key, level, lsize[0], lsize[1], tsize[0], tsize[1]))

    board = coll["boardArt"]["cleaningxl"]
    skipped = []
    for key, _, level, _, _, _, _ in plan:
        if level in level_ids:
            board[str(level)] = dict(BOARD_ART, item=key)
        else:
            skipped.append((level, key))

    new_hall = {
        "id": spec["id"],
        "name": spec["name"],
        "backdrop": spec["backdrop"],
        "shadow": False,
        "glow": False,
        "notes": False,
        "slots": [{"item": key, "levelId": level_id_at(i), "kind": "layer"}
                  for i, (key, _) in enumerate(spec["items"])],
    }
    if spec["id"] in by_id:                     # idempotent re-run
        coll["halls"][coll["halls"].index(by_id[spec["id"]])] = new_hall
        print("hall %-10s %-14s replaced in place" % (spec["id"], spec["name"]))
    else:
        coll["halls"].append(new_hall)
        lv = [level_id_at(i) for i in range(len(spec["items"]))]
        print("hall %-10s %-14s appended (levels %d-%d)"
              % (spec["id"], spec["name"], lv[0], lv[-1]))

    print("\n1 hall, %d slots, %d items, %d boardArt entries"
          % (len(plan), len(coll["items"]), len(plan) - len(skipped)))
    if skipped:
        print("boardArt SKIPPED — no such level in cleaningxl yet: "
              + ", ".join("%d/%s" % (lv, k) for lv, k in skipped))
        print("  Add those entries when the levels are authored, or the hall reveals")
        print("  an item whose level has no art behind its board.")

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return 0

    save(coll)
    print("\nwrote collections.json + collections.js")
    print("Next: verify the hall in the real game at BOTH iPhone and iPad widths")
    print("      (the dev device-switcher cannot test the crop), then update")
    print("      ../../CLAUDE.md §3's hall list.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
