#!/usr/bin/env python3
"""Register halls 9-11 — Cosy Library / Artist's Studio / Sewing Room — in collections.

Run from `memory-match/art/tools/` AFTER extract_layer.py has written every
`art/<hall>/scene/<key>.png` and check_hall_layers.py reports no collisions
(see RUNLOG-HALLS-9-11.md):

    python3 add_halls_9_11.py --dry-run     # report only, touch nothing
    python3 add_halls_9_11.py

This is the sibling of `wire_scene_layers.py`, not a replacement: that one
*converts* the five existing interior halls to layers, this one *appends* three
new ones. It is deliberately a separate file so re-running either cannot undo the
other. It does **not** touch any existing hall, item or boardArt entry, so it
cannot renumber levels or shift the `seenHall` / `seenInstruments` indices that
`progress` is keyed by (see the migration rules in ../../CLAUDE.md §10).

Per item it writes `file` (the existing 512px keyed PNG, for the behind-board
reveal) + `view` (that PNG's pixel size) + `layer` (the full-canvas scene PNG).
Per slot it writes only `item`, `levelId` and `kind: 'layer'` — a layer slot
ignores left/bottom/h, so writing them would imply they still tune something.
Each hall gets `shadow/glow/notes: false`: all three are inert for a layer slot,
and a stale `shadow: true` reads as "this hall draws a contact ellipse" when the
shadow is painted into the art.

**boardArt is written only for levels that exist** in levels_cleaningxl.json when
the script runs. The three halls cover levels 40-54 but the live journey is
mid-rebuild and ends well short of that, so the rest get a hall slot (which
`slotLevelIndex` resolves to -1 and simply never reveals) and no board art.
Fabricating board art for a level that does not exist would be dead data that
looks live. Re-run the script once those levels are authored; it is idempotent.

The reverse case — an entry **orphaned later** by a level deletion — is left
alone, both here and by hand: it is inert (a level that cannot be played is never
looked up) and it correctly pre-wires that level if it comes back. 36-41 are
orphaned as of 2026-07-29, when the journey was cut back to 35 levels.

Idempotent: re-running rewrites the same three halls in place rather than
appending them twice.

Writes both twins byte-identically to what the level-editor's Collections tab
produces:
    collections.json = json.dumps(COLL, indent=2, ensure_ascii=False)   [no \\n]
    collections.js   = 4-line header + "COLLECTIONS = " + that + ";\\n"
"""

import argparse
import json
import os
import sys

from PIL import Image

MM = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
JSON_PATH = os.path.join(MM, "collections.json")
JS_PATH = os.path.join(MM, "collections.js")
LEVELS_PATH = os.path.join(MM, "levels", "levels_cleaningxl.json")

JS_HEADER = (
    "// Collections — item art registry, home halls, and per-level board art.\n"
    "// Single source of truth for home-room.js (main menu) and board-bg.js (art\n"
    "// revealed behind the board). Mirrors collections.json.\n"
    "// Auto-generated by level-editor — edit there; hand-edits get overwritten.\n"
)

# Slot order IS level order. Item keys were checked collision-free against the
# 59-item registry before the art was generated (`globe`, `shelf` and `carpet`
# are taken; these fifteen needed no renames).
HALLS = [
    {
        "id": "library",
        "name": "Cosy Library",
        "backdrop": "art/backdrops/library.jpeg",
        "first": 40,
        "items": [
            ("readinglamp", "Banker's Lamp"),
            ("bookstack", "Stack of Books"),
            ("inkwell", "Inkwell & Quill"),
            ("hourglass", "Hourglass"),
            ("telescope", "Brass Telescope"),
        ],
    },
    {
        "id": "artstudio",
        "name": "Artist's Studio",
        "backdrop": "art/backdrops/artstudio.jpeg",
        "first": 45,
        "items": [
            ("palette", "Paint Palette"),
            ("paintpots", "Paint Pots"),
            ("brushjar", "Jar of Brushes"),
            ("claybust", "Clay Bust"),
            ("easel", "Little Easel"),
        ],
    },
    {
        "id": "sewingroom",
        "name": "Sewing Room",
        "backdrop": "art/backdrops/sewingroom.jpeg",
        "first": 50,
        "items": [
            ("yarnbasket", "Basket of Yarn"),
            ("sewingmachine", "Sewing Machine"),
            ("pincushion", "Pincushion"),
            ("threadspools", "Thread Spools"),
            ("quiltstack", "Stack of Quilts"),
        ],
    },
]

# Matches every other backdrop hall's board art: centred, 82% of the board box.
BOARD_ART = {"cx": 0.5, "cy": 0.5, "h": 0.82}

# A layer is drawn cover-cropped to fill the picture box, so its aspect must match
# the backdrop's or every object in the hall shifts. This is the one preflight
# failure that is invisible in the data and obvious on screen.
ASPECT_TOL = 0.005


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def save(coll):
    body = json.dumps(coll, indent=2, ensure_ascii=False)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        f.write(body)
    with open(JS_PATH, "w", encoding="utf-8") as f:
        f.write(JS_HEADER + "COLLECTIONS = " + body + ";\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    coll = load(JSON_PATH)
    new_ids = {h["id"] for h in HALLS}
    existing = {h["id"] for h in coll["halls"]}

    levels = load(LEVELS_PATH)
    level_ids = {lv["id"] for lv in (levels["levels"] if isinstance(levels, dict) else levels)}

    problems, plan = [], []
    for spec in HALLS:
        backdrop = os.path.join(MM, spec["backdrop"])
        if not os.path.isfile(backdrop):
            problems.append("%s: missing backdrop %s" % (spec["id"], spec["backdrop"]))
            continue
        bw, bh = Image.open(backdrop).size

        for i, (key, name) in enumerate(spec["items"]):
            level = spec["first"] + i
            tight_rel = "art/%s/%s.png" % (spec["id"], key)
            layer_rel = "art/%s/scene/%s.png" % (spec["id"], key)
            tight_abs, layer_abs = os.path.join(MM, tight_rel), os.path.join(MM, layer_rel)

            # An item key already in the registry would be a silent collision: two
            # halls would draw the same art and boardArt would be ambiguous.
            if key in coll["items"] and spec["id"] not in existing:
                problems.append("item key %r is already registered — rename it" % key)
            for rel, abs_ in ((tight_rel, tight_abs), (layer_rel, layer_abs)):
                if not os.path.isfile(abs_):
                    problems.append("%s: missing %s" % (spec["id"], rel))
            if not (os.path.isfile(tight_abs) and os.path.isfile(layer_abs)):
                continue

            tim, lim = Image.open(tight_abs), Image.open(layer_abs)
            for rel, im in ((tight_rel, tim), (layer_rel, lim)):
                if im.mode != "RGBA":
                    problems.append("%s is %s, expected RGBA" % (rel, im.mode))
            delta = abs(lim.size[0] / lim.size[1] - bw / bh)
            if delta > ASPECT_TOL:
                problems.append(
                    "%s aspect %.4f vs backdrop %.4f (off by %.4f) — every item in "
                    "the hall will mis-register" % (layer_rel, lim.size[0] / lim.size[1],
                                                    bw / bh, delta))

            # A levelId may live in only one hall (CLAUDE.md §3).
            for hall in coll["halls"]:
                if hall["id"] in new_ids:
                    continue
                for slot in hall["slots"]:
                    if slot["levelId"] == level:
                        problems.append("level %d is already claimed by hall %s"
                                        % (level, hall["id"]))
            plan.append((spec, key, name, level, tight_rel, layer_rel, tim.size, lim.size))

    if problems:
        print("PREFLIGHT FAILED:", file=sys.stderr)
        for p in sorted(set(problems)):
            print("  - " + p, file=sys.stderr)
        return 1

    for spec, key, name, level, tight_rel, layer_rel, tsize, lsize in plan:
        coll["items"][key] = {
            "name": name,
            "file": tight_rel,
            "view": {"w": tsize[0], "h": tsize[1]},
            "layer": layer_rel,
        }
        print("  %-11s %-14s L%-3d layer %dx%d  file %dx%d" %
              (spec["id"], key, level, lsize[0], lsize[1], tsize[0], tsize[1]))

    board = coll["boardArt"]["cleaningxl"]
    skipped = []
    for spec, key, _, level, _, _, _, _ in plan:
        if level in level_ids:
            board[str(level)] = dict(BOARD_ART, item=key)
        else:
            skipped.append((level, key))

    halls_by_id = {h["id"]: h for h in coll["halls"]}
    for spec in HALLS:
        hall = {
            "id": spec["id"],
            "name": spec["name"],
            "backdrop": spec["backdrop"],
            "shadow": False,
            "glow": False,
            "notes": False,
            "slots": [{"item": key, "levelId": spec["first"] + i, "kind": "layer"}
                      for i, (key, _) in enumerate(spec["items"])],
        }
        if spec["id"] in halls_by_id:                     # idempotent re-run
            coll["halls"][coll["halls"].index(halls_by_id[spec["id"]])] = hall
            print("hall %-11s %-18s replaced in place" % (spec["id"], spec["name"]))
        else:
            coll["halls"].append(hall)
            print("hall %-11s %-18s appended (levels %d-%d)"
                  % (spec["id"], spec["name"], spec["first"], spec["first"] + 4))

    print("\n%d halls, %d slots, %d items, %d boardArt entries"
          % (len(HALLS), len(plan), len(coll["items"]), len(plan) - len(skipped)))
    if skipped:
        print("boardArt SKIPPED — no such level in cleaningxl yet: "
              + ", ".join("%d/%s" % (lv, k) for lv, k in skipped))
        print("  Add those entries when the levels are authored, or the hall reveals")
        print("  an item whose level has no art behind its board.")

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return 0

    save(coll)
    print("\nwrote collections.json + collections.js")
    print("Next: verify the three halls in the real game at BOTH iPhone and iPad")
    print("      widths (the dev device-switcher cannot test the crop — see RUNLOG.md),")
    print("      then update ../../CLAUDE.md §3's hall list.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
