#!/usr/bin/env python3
"""Convert the five interior-room halls from placed items to scene layers.

Run from `memory-match/art/tools/` AFTER extract_layer.py has written every
`art/<hall>/scene/<key>.png` and refreshed the tight `art/<hall>/<key>.png`
(see ../SCENE-LAYERS-PLAN.md):

    python3 wire_scene_layers.py --dry-run     # report only, touch nothing
    python3 wire_scene_layers.py

Per item it sets `layer` to the full-canvas scene PNG and leaves `file`/`view`
alone. Per slot it sets `kind: 'layer'` and drops `left`/`bottom`/`h`, which a
layer slot ignores — leaving them would imply they still tune something.

`file` deliberately keeps the original 512px keyed render: cropping the item out
of the scene yields only ~265px, and board-bg.js draws the behind-board reveal at
up to 0.9 * board height, where that is visibly soft. The cost is that a hall's
object and its behind-board object are two renders of the same idea — a knowing
exception to CLAUDE.md §3's "must not drift", taken because the alternative is
blurry board art. See ../SCENE-LAYERS-PLAN.md "Board art resolution".

Also clears each hall's `shadow` and `floatPx`. Both go inert for layer slots
(home-room.js gives a layer no pedestal, no shadow and no bob), and a stale
`shadow: true` reads as "this hall draws a contact ellipse" when the shadow is now
painted into the art.

Idempotent, and **safe to re-run after regenerating art** — it rewrites the same
five halls in place rather than appending. It only ever touches those five: item
keys, level ids and hall order are read from the existing collections.json, so it
cannot renumber levels or shift `seenHall` indices.

NOT a replacement for wire_halls.py — that one bootstraps these halls as placed
items from seed geometry. Running it after this reverts the conversion.

Writes both twins byte-identically to what the level-editor's Collections tab
produces:
    collections.json = json.dumps(COLL, indent=2, ensure_ascii=False)   [no \\n]
    collections.js   = 4-line header + "COLLECTIONS = " + that + ";\\n"
"""

import argparse
import json
import os
import sys

from PIL import Image

MM = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
JSON_PATH = os.path.join(MM, "collections.json")
JS_PATH = os.path.join(MM, "collections.js")

JS_HEADER = (
    "// Collections — item art registry, home halls, and per-level board art.\n"
    "// Single source of truth for home-room.js (main menu) and board-bg.js (art\n"
    "// revealed behind the board). Mirrors collections.json.\n"
    "// Auto-generated by level-editor — edit there; hand-edits get overwritten.\n"
)

HALL_IDS = ["attic", "kitchen", "greenhouse", "musicroom", "workshop"]

# A layer is drawn cover-cropped to fill the picture box, so its aspect must match
# the backdrop's or every object in the hall shifts. This is the one preflight
# failure that is invisible in the data and obvious on screen.
ASPECT_TOL = 0.005


def load():
    with open(JSON_PATH, encoding="utf-8") as f:
        return json.load(f)


def save(coll):
    body = json.dumps(coll, indent=2, ensure_ascii=False)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        f.write(body)
    with open(JS_PATH, "w", encoding="utf-8") as f:
        f.write(JS_HEADER + "COLLECTIONS = " + body + ";\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    coll = load()
    halls = {h["id"]: h for h in coll["halls"]}
    problems = []
    plan = []

    for hid in HALL_IDS:
        hall = halls.get(hid)
        if hall is None:
            problems.append("hall not found in collections.json: " + hid)
            continue
        backdrop = hall.get("backdrop")
        if not backdrop or not os.path.isfile(os.path.join(MM, backdrop)):
            problems.append("%s: missing backdrop %s" % (hid, backdrop))
            continue
        bw, bh = Image.open(os.path.join(MM, backdrop)).size

        for slot in hall["slots"]:
            key = slot["item"]
            layer_rel = "art/%s/scene/%s.png" % (hid, key)
            tight_rel = coll["items"][key]["file"]
            layer_abs = os.path.join(MM, layer_rel)
            tight_abs = os.path.join(MM, tight_rel)

            if not os.path.isfile(layer_abs):
                problems.append("%s: missing layer %s — run extract_layer.py first"
                                % (hid, layer_rel))
                continue
            lim = Image.open(layer_abs)
            if lim.mode != "RGBA":
                problems.append("%s is %s, expected RGBA" % (layer_rel, lim.mode))
            delta = abs(lim.size[0] / lim.size[1] - bw / bh)
            if delta > ASPECT_TOL:
                problems.append(
                    "%s aspect %.4f vs backdrop %.4f (off by %.4f) — every item in "
                    "the hall will mis-register" % (layer_rel, lim.size[0] / lim.size[1],
                                                    bw / bh, delta)
                )
            if not os.path.isfile(tight_abs):
                problems.append("%s: missing tight crop %s" % (hid, tight_rel))
                continue
            tim = Image.open(tight_abs)
            if tim.mode != "RGBA":
                problems.append("%s is %s, expected RGBA" % (tight_rel, tim.mode))
            plan.append((hid, key, slot, layer_rel, lim.size, tim.size))

    if problems:
        print("PREFLIGHT FAILED:", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        return 1

    for hid, key, slot, layer_rel, lsize, tsize in plan:
        item = coll["items"][key]
        item["layer"] = layer_rel
        # `file` and `view` are left as they are on purpose — see the module docstring.
        dropped = [k for k in ("left", "bottom", "h") if k in slot]
        for k in dropped:
            slot.pop(k)
        slot["kind"] = "layer"
        print("  %-9s %-13s layer %dx%d  file %dx%d (kept)  dropped %s"
              % (hid, key, lsize[0], lsize[1], tsize[0], tsize[1],
                 ",".join(dropped) or "-"))

    for hid in HALL_IDS:
        hall = halls[hid]
        # Match Childhood/Bedroom: a layer hall draws no pedestal, shadow or bob.
        hall["shadow"] = False
        hall.pop("floatPx", None)
        hall.pop("floatSec", None)
        print("hall %-11s %-22s shadow=False, floatPx dropped" % (hid, hall["name"]))

    print("\n%d halls, %d items, %d slots converted"
          % (len(HALL_IDS), len(coll["items"]), len(plan)))

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return 0

    save(coll)
    print("\nwrote collections.json + collections.js")
    print("Next: verify in level-editor/ Collections tab at BOTH iPhone and iPad,")
    print("      then update CLAUDE.md §3 (see ../SCENE-LAYERS-PLAN.md).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
