#!/usr/bin/env python3
"""Register the 5 interior-room halls into collections.json + collections.js.

Levels 34-58, one hall per five: attic 34-38, kitchen 39-43, greenhouse 44-48,
musicroom 49-53, workshop 54-58. The plan specified 30-54, but the Bedroom hall
landed on 30-33 first and two halls cannot share a levelId, so these shifted +4.

Run from `memory-match/art/tools/` AFTER the backdrops and keyed item PNGs are in
place (see ../NEW-HALLS-PLAN.md):

    python3 wire_halls.py --dry-run     # report only, touch nothing
    python3 wire_halls.py

Writes both twins byte-identically to what the level-editor's Collections tab
produces:
    collections.json = json.dumps(COLL, indent=2, ensure_ascii=False)   [no \\n]
    collections.js   = 4-line header + "COLLECTIONS = " + that + ";\\n"

Idempotent: re-running replaces the five halls and their items/boardArt rather
than appending duplicates, so it is safe to run again after regenerating art.

The slot geometry it writes is a SEED, not a final answer. Every backdrop was
prompted with the same five bare surfaces (far left floor / left-of-centre bench
/ centre / mid-height right shelf / right floor), so the seeds land in the right
neighbourhood — then nudge in level-editor/ (Collections tab) and check at BOTH
iPhone and iPad, because iPad crops ~38% off the top of a 0.5625 backdrop.

Geometry reminder (CLAUDE.md §3): `left` is the item's horizontal CENTRE,
`bottom` is its BASE, `h` is its height as % of the picture box. The resulting
on-screen width % is h * (1024/576) * (imgW/imgH) — this script prints it so an
overshoot is visible before you open the editor.
"""

import argparse
import json
import os
import sys

from PIL import Image

MM = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
JSON_PATH = os.path.join(MM, "collections.json")
JS_PATH = os.path.join(MM, "collections.js")

JS_HEADER = (
    "// Collections — item art registry, home halls, and per-level board art.\n"
    "// Single source of truth for home-room.js (main menu) and board-bg.js (art\n"
    "// revealed behind the board). Mirrors collections.json.\n"
    "// Auto-generated by level-editor — edit there; hand-edits get overwritten.\n"
)

# Shared seed for the five painted surfaces, in slot order.
# (left = horizontal centre, bottom = base, h = height — all % of the picture box)
# The two OUTER slots are the tight ones: `left` is a centre, so a wide item at
# left=88 runs off the picture. They sit at 16/84 rather than hugging the edge.
SEED = [
    {"left": 16, "bottom": 8, "h": 12.0},   # far left, on the floor / a crate
    {"left": 34, "bottom": 30, "h": 11.0},  # left of centre, on the bench / counter
    {"left": 50, "bottom": 29, "h": 12.0},  # centre, on the stool / trivet
    {"left": 78, "bottom": 46, "h": 10.0},  # right, mid-height shelf
    {"left": 84, "bottom": 7, "h": 11.0},   # right, on the floor
]

# hall id -> (display name, backdrop file, first level, [(item key, display name)])
HALLS = [
    (
        "attic",
        "Cozy Attic",
        "art/backdrops/cozy-attic.jpeg",
        34,
        [
            ("rockinghorse", "Rocking Horse"),
            ("globe", "Antique Globe"),
            ("teddybear", "Teddy Bear"),
            ("oillamp", "Oil Lamp"),
            ("trunk", "Steamer Trunk"),
        ],
    ),
    (
        "kitchen",
        "Grandma's Kitchen",
        "art/backdrops/kitchen.jpeg",
        39,
        [
            ("kettle", "Copper Kettle"),
            ("pie", "Apple Pie"),
            ("mixingbowl", "Mixing Bowl"),
            ("jamjars", "Jam Jars"),
            ("cat", "Sleeping Cat"),
        ],
    ),
    (
        "greenhouse",
        "Victorian Greenhouse",
        "art/backdrops/greenhouse.jpeg",
        44,
        [
            ("wateringcan", "Watering Can"),
            ("orchid", "Moth Orchid"),
            ("claypots", "Clay Pots"),
            ("trowelgloves", "Trowel & Gloves"),
            ("cloche", "Glass Cloche"),
        ],
    ),
    (
        "musicroom",
        "Music Room",
        "art/backdrops/music-room.jpeg",
        49,
        [
            ("gramophone", "Gramophone"),
            ("cello", "Cello"),
            ("metronome", "Metronome"),
            ("sheetmusic", "Sheet Music"),
            ("accordion", "Accordion"),
        ],
    ),
    (
        "workshop",
        "Toy Workshop",
        "art/backdrops/workshop.jpeg",
        54,
        [
            ("toytrain", "Wooden Train"),
            ("tinrobot", "Tin Robot"),
            ("kite", "Paper Kite"),
            ("jackinthebox", "Jack-in-the-Box"),
            ("toolbox", "Toolbox"),
        ],
    ),
]

NEW_HALL_IDS = {h[0] for h in HALLS}
NEW_ITEM_KEYS = {k for h in HALLS for k, _ in h[4]}
BACKDROP_ASPECT = 1024.0 / 576.0


def load():
    with open(JSON_PATH, encoding="utf-8") as f:
        return json.load(f)


def save(coll):
    body = json.dumps(coll, indent=2, ensure_ascii=False)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        f.write(body)
    with open(JS_PATH, "w", encoding="utf-8") as f:
        f.write(JS_HEADER + "COLLECTIONS = " + body + ";\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    coll = load()
    problems = []

    # --- preflight: every asset must exist, no key may collide -------------
    existing_items = set(coll["items"]) - NEW_ITEM_KEYS
    sizes = {}
    for hid, _name, backdrop, _first, items in HALLS:
        if not os.path.isfile(os.path.join(MM, backdrop)):
            problems.append("missing backdrop: " + backdrop)
        else:
            bw, bh = Image.open(os.path.join(MM, backdrop)).size
            if abs(bw / bh - 0.5625) > 0.01:
                problems.append(
                    "%s aspect %.4f, want 0.5625 (576x1024)" % (backdrop, bw / bh)
                )
        for key, _disp in items:
            if key in existing_items:
                problems.append("item key collides with an existing item: " + key)
            rel = "art/%s/%s.png" % (hid, key)
            full = os.path.join(MM, rel)
            if not os.path.isfile(full):
                problems.append("missing item art: " + rel)
                continue
            im = Image.open(full)
            if im.mode != "RGBA":
                problems.append("%s is %s, expected RGBA (not keyed?)" % (rel, im.mode))
            sizes[key] = im.size

    if problems:
        print("PREFLIGHT FAILED:", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        return 1

    # --- drop any previous run's data so this is idempotent ----------------
    coll["halls"] = [h for h in coll["halls"] if h.get("id") not in NEW_HALL_IDS]
    for k in NEW_ITEM_KEYS:
        coll["items"].pop(k, None)

    board_art = coll["boardArt"]["cleaningxl"]
    overwritten = []
    geometry_warnings = []

    for hid, name, backdrop, first, items in HALLS:
        slots = []
        prev = None
        for i, (key, disp) in enumerate(items):
            w, h_px = sizes[key]
            coll["items"][key] = {
                "name": disp,
                "file": "art/%s/%s.png" % (hid, key),
                "view": {"w": w, "h": h_px},
            }
            level_id = first + i
            s = dict(SEED[i])
            slots.append(
                {
                    "item": key,
                    "levelId": level_id,
                    "left": s["left"],
                    "bottom": s["bottom"],
                    "h": s["h"],
                }
            )
            # `left` is the CENTRE, so the real constraint is the edges, not the
            # width: a 33%-wide item at left=88 runs off the right of the picture.
            width_pct = s["h"] * BACKDROP_ASPECT * (w / h_px)
            l_edge = s["left"] - width_pct / 2.0
            r_edge = s["left"] + width_pct / 2.0
            flags = []
            if l_edge < 0 or r_edge > 100:
                flags.append(
                    "OFF-FRAME (%.1f..%.1f) — reduce h or pull left in"
                    % (l_edge, r_edge)
                )
            # Overlap only matters between items sharing a visual plane; a shelf
            # item above a floor item may overlap horizontally and look fine.
            if (
                prev
                and abs(s["bottom"] - prev["bottom"]) < 8
                and l_edge < prev["r_edge"]
            ):
                flags.append("OVERLAPS %s on the same plane" % prev["key"])
            if flags:
                geometry_warnings.append("%s/%s: %s" % (hid, key, "; ".join(flags)))
            print(
                "  %-14s lvl %2d  left=%-3s bottom=%-3s h=%-5s => w=%.1f%% [%.1f..%.1f]%s"
                % (
                    key,
                    level_id,
                    s["left"],
                    s["bottom"],
                    s["h"],
                    width_pct,
                    l_edge,
                    r_edge,
                    "  <-- " + "; ".join(flags) if flags else "",
                )
            )
            prev = {"key": key, "bottom": s["bottom"], "r_edge": r_edge}

            if str(level_id) in board_art:
                overwritten.append(
                    "%d (was %s)" % (level_id, board_art[str(level_id)]["item"])
                )
            board_art[str(level_id)] = {
                "item": key,
                "cx": 0.5,
                "cy": 0.5,
                "h": 0.9 if h_px >= w else 0.82,
            }

        coll["halls"].append(
            {
                "id": hid,
                "name": name,
                "backdrop": backdrop,
                "shadow": True,
                "glow": False,
                "notes": False,
                "floatPx": 0,  # the user's "items must not bob" requirement
                "slots": slots,
            }
        )
        print("hall %-11s %s  levels %d-%d" % (hid, name, first, first + 4))

    coll["boardArt"]["cleaningxl"] = {
        k: board_art[k] for k in sorted(board_art, key=int)
    }

    if geometry_warnings:
        print("\nGEOMETRY WARNINGS (seeds still written — fix in the editor):")
        for g in geometry_warnings:
            print("  - " + g)

    if overwritten:
        print("\nboardArt OVERWRITTEN for levels: " + ", ".join(overwritten))
    print(
        "\n%d halls, %d items, boardArt levels %s"
        % (
            len(coll["halls"]),
            len(coll["items"]),
            "%s-%s"
            % (
                min(int(k) for k in coll["boardArt"]["cleaningxl"]),
                max(int(k) for k in coll["boardArt"]["cleaningxl"]),
            ),
        )
    )

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return 0

    save(coll)
    print("\nwrote collections.json + collections.js")
    print("Next: level-editor/ -> Collections tab, nudge placement, check iPhone+iPad")
    return 0


if __name__ == "__main__":
    sys.exit(main())
